### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by attiks**
- redis added
- solr connects using container dns
- database is using relative directory
- web is running on a different port to avoid local problems
- dns no longer needed
- drush is installed using composer
- build script split in 2 parts: web and db

### CODE REVIEW

**Comment by emmajane** [comment]
Reminder to whoever is reviewing the PR: check this against the Aegir deployment process; specifically with respect to the composer install and version of Drush.

**Comment by emmajane** [comment]
See also Pedro's notes on https://github.com/humanitarianresponse/hr_docker/pull/11 re. installing Drush with Composer.

**Comment by teodorescuserban** [comment]
Commit `Add redis image`: you either publish ports (to be able to access the container on a specific port) or you link from redis container (in which case "redis" is resolved as that container ip and the redis port is the port exposed from container - 6379)

Beware: linking containers is ok on dev side (easier to start things up) but:
1. it is not recommended to use in production
2. dev env should match as much as possible with prod (this applies by the way to the commit `Install drush using composer` - building stuff locally is a bad idea in general as you can end up with different content on dev containers and prod ones

`Use container name` commit: is this for dev only? If so, ok. If for prod, not ok.

`Split build into web and db` commit: split is a good idea, but it would have been even better if you kept the whole thing in a single script and you used functions :)

**Comment by attiks** [comment]
You're absolutely right, but I did it mainly for my local install, when I have time I'll improve it to mimic live version

**Comment by attiks** [comment]
N/A

**Pull request closed without merging**
